name: Staging Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [react-node-postgres-vercel, exp-api-deploy]
  pull_request:
    branches: [react-node-postgres-vercel, exp-api-deploy]
    types: [opened]

env:
  NODE_VERSION: 18.13.0

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Build and push image to ghcr.io
        run: |
          docker compose -f docker-compose.stage.yml build api
          docker images
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/coffeemasters-api
      - name: check current dir path
        run: pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-file
          path: |
            docker-compose.stage.yml

  deploy-staging:
    needs: build-push
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-compose-file
          path: ./coffeemasters
      - name: transfer files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP_ADD }}
          # host: ${{ secrets.DO_DROPLET_DOMAIN }}
          username: ${{ secrets.DO_DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          source: './coffeemasters'
          target: '~/'
      - name: run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP_ADD }}
          # host: ${{ secrets.DO_DROPLET_DOMAIN }}
          username: ${{ secrets.DO_DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/coffeemasters
            docker compose -f docker-compose.stage.yml down
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker compose -f docker-compose.stage.yml pull api
            docker compose -f docker-compose.stage.yml up -d
            docker ps -a
